---
title: "HeartDisease"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r}
#install.packages("summarytools")
#install.packages("rattle")

library(ggplot2)
library(tidyverse)
library(corrplot)
library(caret)
library(summarytools)
library(e1071)
library(RSNNS)
library(RWeka)
library(rattle)
#library(mlr)
```


### Load the dataset
```{r}
data <- read.csv(file = "./data/heart.csv",sep = ",",header = T) 
```


### Analysing the data
```{r}
# Summary statistics (mean, sd, quantiles, max and min)
data.summary <- summarytools::descr(data)[1:7,]

# The first variable is loaded with a strange name. Let's correct that!
names(data)[1] <- "age"

# Are there missing values?
data[!complete.cases(data),] 

# Is the class variable balanced?
table(data$target)

# Visual inspection
plot.age<- ggplot(data = data, aes(x = age ,fill=factor(target)))+
  geom_histogram(bins = 30)+
  labs(title="Age histogram",x="Years", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.age

plot.sex<- ggplot(data = data, aes(x = sex, fill=factor(target)))+
  geom_histogram(bins = 3)+
  labs(title="Sex histogram",x="Sex", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.sex

plot.cp<- ggplot(data = data, aes(x = cp, fill=factor(target)))+
  geom_histogram(bins = 7)+
  labs(title="Chest pain histogram",x="Pain level", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.cp

plot.trestbps<- ggplot(data = data, aes(x = trestbps, fill=factor(target)))+
  geom_histogram(bins = 40)+
  labs(title="Resting blood pressure histogram",x="mm Hg", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.trestbps

plot.chol<- ggplot(data = data, aes(x = chol, fill=factor(target)))+
  geom_histogram(bins = 40)+
  labs(title="Serum cholesterol histogram",x="mm/dl", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.chol

plot.fbs<- ggplot(data = data, aes(x = fbs, fill=factor(target)))+
  geom_histogram(bins = 3)+
  labs(title="Fasting blood sugar histogram",x="FBS > 120 mg/dl", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.fbs

plot.restecg<- ggplot(data = data, aes(x = restecg, fill=factor(target)))+
  geom_histogram(bins = 5)+
  labs(title="Resting electrocardiographic results histogram",x="Value", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.restecg

plot.thalach<- ggplot(data = data, aes(x = thalach, fill=factor(target)))+
  geom_histogram(bins = 40)+
  labs(title="Maximum heart rate achieved histogram",x="bpm", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.thalach

plot.exang<- ggplot(data = data, aes(x = exang, fill=factor(target)))+
  geom_histogram(bins = 3)+
  labs(title="Exercise induced angina histogram",x="Exang", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.exang

plot.oldpeak<- ggplot(data = data, aes(x = oldpeak, fill=factor(target)))+
  geom_histogram(bins = 40)+
  labs(title="Exercise systolic depression  histogram",x="Oldpeak", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.oldpeak

plot.slope<- ggplot(data = data, aes(x = slope, fill=factor(target)))+
  geom_histogram(bins = 5)+
  labs(title="Exercise ST segment slope histogram",x="Slope", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.slope

plot.ca<- ggplot(data = data, aes(x = ca, fill=factor(target)))+
  geom_histogram(bins = 9)+
  labs(title="Fluoroscopy coloured major vessels histogram",x="Ca", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.ca

plot.thal<- ggplot(data = data, aes(x = thal, fill=factor(target)))+
  geom_histogram(bins = 7)+
  labs(title="Thal histogram",x="Thal", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.thal

plot.target<- ggplot(data = data, aes(x = target, fill=factor(target)))+
  geom_histogram(bins = 3)+
  labs(title="Heart disease histogram",x="Presence of heart disease", y = "Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "Heart disease")
plot.target
```


<!-- ```{r} -->
<!-- data<-data %>% -->
<!--   filter(restecg!=2) -->
<!-- table(data$restecg) -->
<!-- ``` -->


### Data randomization
```{r}
#We set a fixed seed to get the same result every time. 
set.seed(42)

#We shuffle the row indexes.
rows <- sample(nrow(data))
data <- data[rows, ]
```


### Variable normalization
```{r}
# Normalization function (min = 0, max = 1)
normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}

data$age <- normalize(data$age)
data$cp <- normalize(data$cp)
data$restecg <- normalize(data$restecg)
data$chol <- normalize(data$chol)
data$trestbps <- normalize(data$trestbps)
data$thalach <- normalize(data$thalach)
data$oldpeak <- normalize(data$oldpeak)
data$slope <- normalize(data$slope)
data$ca <- normalize(data$ca)
data$thal <- normalize(data$thal)
```

### Correlations and dataset split
```{r}
# Correlation matrix
cor.matrix <- cor(data)

#Let's plot the correlations!
cor.plot <- corrplot(cor.matrix, type = "upper", tl.col = "darkblue", tl.srt = 45)

#How are the explanatory variables related with the target?
cor.target <- as.data.frame(cor.matrix[,14]) 
cor.target

#Also, since the target variable is binary, let's make it categorical so that the classifiers do not think we are trying to perform a regression. 
data$target <- as.factor(data$target)

#Data for the classifier
data.model.1 <- data

#Let's keep those with higher correlation coefficients!
#Top 10
data.model.2 <- data %>% 
  select("age","sex","cp","thalach", "exang","oldpeak","slope","ca","thal","target")
#Top 8
data.model.3 <- data %>% 
  select("cp", "thalach", "exang","oldpeak","slope","ca","thal","target")

```

### Data split 
```{r}
set.seed(42)
#Data split: 80% for training, 20% for testing. 
ind <- createDataPartition(data.model.1$target, p = 0.8, list = FALSE)
train.data.1 <- data.model.1[ind,]
test.data.1 <- data.model.1[-ind,]

#We repeat the process for the other two datasets:
train.data.2 <- data.model.2[ind,]
test.data.2 <- data.model.2[-ind,]

train.data.3 <- data.model.3[ind,]
test.data.3 <- data.model.3[-ind,]
```



### kNN
```{r}
# Let's use 5-fold cross-validation!
control <- trainControl(method  = "cv", number  = 5)

# First dataset (all variables)
# Training
knn.model.1 <- caret::train(target ~ ., data = train.data.1, trControl = control, metric = "Accuracy", method = "knn", tuneGrid = expand.grid(k = 1:15))
knn.model.1

#Testing
knn.pred.1 <- predict(knn.model.1,test.data.1)

#Confusion matrix
caret::confusionMatrix(test.data.1$target, knn.pred.1, positive = "1")

#We repeat the process for the two other datasets.
knn.model.2 <- caret::train(target ~ ., data = train.data.2, trControl = control, metric = "Accuracy", method = "knn", tuneGrid = expand.grid(k = 1:15))
knn.model.2
knn.pred.2 <- predict(knn.model.2,test.data.2)
caret::confusionMatrix(test.data.2$target, knn.pred.2, positive = "1")

knn.model.3 <- caret::train(target ~ ., data = train.data.3, trControl = control, metric = "Accuracy", method = "knn", tuneGrid = expand.grid(k = 1:15))
knn.model.3
knn.pred.3 <- predict(knn.model.3,test.data.3)
caret::confusionMatrix(test.data.3$target, knn.pred.3, positive = "1")

```

### Multi-Layer Perceptron
```{r}
set.seed(42)
# Let's use 5-fold cross-validation!
control <- trainControl(method  = "cv", number  = 5)

# First dataset (all variables)
# Training
mlp.model.1 <- caret::train(target ~ ., data = train.data.1, trControl = control, metric = "Accuracy", method = "mlp", tuneGrid = expand.grid(size = 1:15))
mlp.model.1

#Testing
mlp.pred.1 <- predict(mlp.model.1,test.data.1)

#Confusion matrix
caret::confusionMatrix(test.data.1$target, mlp.pred.1, positive = "1")

#We repeat the process for the two other datasets.
mlp.model.2 <- caret::train(target ~ ., data = train.data.2, trControl = control, metric = "Accuracy", method = "mlp", tuneGrid = expand.grid(size = 1:15))
mlp.model.2
mlp.pred.2 <- predict(mlp.model.2,test.data.2)
caret::confusionMatrix(test.data.2$target, mlp.pred.2, positive = "1")

mlp.model.3 <- caret::train(target ~ ., data = train.data.3, trControl = control, metric = "Accuracy", method = "mlp", tuneGrid = expand.grid(size = 1:15))
mlp.model.3
mlp.pred.3 <- predict(mlp.model.3,test.data.3)
caret::confusionMatrix(test.data.3$target, mlp.pred.3, positive = "1")
```


### Decision Tree
```{r}
set.seed(42)
# Let's use 5-fold cross-validation!
control <- trainControl(method  = "cv", number  = 5)

# First dataset (all variables)
# Training
j48.model.1 <- caret::train(target ~ ., data = train.data.1, trControl = control, metric = "Accuracy", method = "J48", tuneGrid = expand.grid(C = seq(0.1, 0.5, by=0.05), M = 1:10))
j48.model.1
plot(j48.model.1)
plot(j48.model.1$finalModel)

#Testing
j48.pred.1 <- predict(j48.model.1,test.data.1)

#Confusion matrix
caret::confusionMatrix(test.data.1$target, j48.pred.1, positive = "1")

#We repeat the process for the two other datasets.
j48.model.2 <- caret::train(target ~ ., data = train.data.2, trControl = control, metric = "Accuracy", method = "J48", tuneGrid = expand.grid(C = seq(0.1, 0.5, by=0.05), M = 1:10))
j48.model.2
plot(j48.model.2)
plot(j48.model.2$finalModel)
j48.pred.2 <- predict(j48.model.2,test.data.2)
caret::confusionMatrix(test.data.2$target, j48.pred.2, positive = "1")

j48.model.3 <- caret::train(target ~ ., data = train.data.3, trControl = control, metric = "Accuracy", method = "J48", tuneGrid = expand.grid(C = seq(0.1, 0.5, by=0.05), M = 1:10))
j48.model.3
plot(j48.model.3)
plot(j48.model.3$finalModel)
j48.pred.3 <- predict(j48.model.3,test.data.3)
caret::confusionMatrix(test.data.3$target, j48.pred.3, positive = "1")

```













